sonar.projectKey=Accredifysg_PHP-RDF-Canonicalize
sonar.projectName=PHP-RDF-Canonicalize

# sources and tests
sonar.sources=src
sonar.tests=tests

# coverage
sonar.php.coverage.reportPaths=coverage_BE/clover.xml
sonar.php.tests.reportPath=junit_BE/junit.xml
sonar.exclusions=coverage_BE/**,junit_BE/**
