name: Main

on:
  push:
    branches: [main]

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/ci.yml

  sonar:
    needs: ci
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # full history for SCM blame

      - name: Download Backend Coverage Report
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.ci.outputs.backend-coverage-artifact-name }}
          path: coverage_BE

      - name: Download Backend JUnit Report
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.ci.outputs.backend-junit-artifact-name }}
          path: junit_BE

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
